// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRMivmZyieTwZfc9JVW2mTTyg4FLDsClk',
    appId: '1:941110850287:web:1b2fceae909699d31be11a',
    messagingSenderId: '941110850287',
    projectId: 'fish-pond-23c6c',
    authDomain: 'fish-pond-23c6c.firebaseapp.com',
    storageBucket: 'fish-pond-23c6c.firebasestorage.app',
    measurementId: 'G-CGERBD962E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ7kSowGR-6eshyDZRGZu-fTTfizB9Lbk',
    appId: '1:941110850287:android:34a77b4c73abf5321be11a',
    messagingSenderId: '941110850287',
    projectId: 'fish-pond-23c6c',
    storageBucket: 'fish-pond-23c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAucVQTguF8poUFUlZ4KKU9JAGP7wJWcmk',
    appId: '1:941110850287:ios:67dde935842a8bf71be11a',
    messagingSenderId: '941110850287',
    projectId: 'fish-pond-23c6c',
    storageBucket: 'fish-pond-23c6c.firebasestorage.app',
    iosBundleId: 'com.example.fishpond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAucVQTguF8poUFUlZ4KKU9JAGP7wJWcmk',
    appId: '1:941110850287:ios:67dde935842a8bf71be11a',
    messagingSenderId: '941110850287',
    projectId: 'fish-pond-23c6c',
    storageBucket: 'fish-pond-23c6c.firebasestorage.app',
    iosBundleId: 'com.example.fishpond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRMivmZyieTwZfc9JVW2mTTyg4FLDsClk',
    appId: '1:941110850287:web:95310a89499402a61be11a',
    messagingSenderId: '941110850287',
    projectId: 'fish-pond-23c6c',
    authDomain: 'fish-pond-23c6c.firebaseapp.com',
    storageBucket: 'fish-pond-23c6c.firebasestorage.app',
    measurementId: 'G-K6TMMV4BQ8',
  );
}
